package server.servlet.json.template.model.weekly.activity;


import engine.model.activity.weekly.activity.WeeklyActivity;
import engine.model.boat.Boat;
import server.servlet.json.template.model.boat.BoatJson;

import java.time.format.DateTimeFormatter;
import java.util.List;

public class WeeklyActivityJson {
    public final String id;
    public final String name;
    public final String startTime;
    public final String endTime;
    public final int boatType;
    public final String boatTypeDescription;
    public final boolean isAutoGenerated;


    public WeeklyActivityJson(WeeklyActivity activity) {
        this.id  = activity.getId();
        this.name = activity.getName();
        this.startTime = activity.getStartTime().format(DateTimeFormatter.ofPattern("HH:mm"));
        this.endTime = activity.getEndTime().format(DateTimeFormatter.ofPattern("HH:mm"));
        this.boatType = Boat.eBoatType.getIntFromBoatType(activity.getBoatType());
        this.isAutoGenerated = activity.isAutoGenerated();

        if(activity.getBoatType() != null) {
            this.boatTypeDescription = activity.getBoatType().getTypeDescription() +
                    " (" + activity.getBoatType().getShortCode() + ")";
        }
        else {
            this.boatTypeDescription = "None";
        }
    }
}
